#include <stdio.h> // Provides printf() function
#include <signal.h> // Provides signal() and signal names like SIGINT
#include <unistd.h> // Provides getpid() and sleep()

void handle_signal(int sig) // Function that handles the received signal
{
if (sig == SIGINT) // Checks if the signal is SIGINT
printf("\nSIGINT received!\n"); // Prints a message when SIGINT is received

else if (sig == SIGTERM) // Checks if the signal is SIGTERM
printf("\nSIGTERM received!\n");

// Prints a message when SIGTERM is received
else if (sig == SIGUSR1) // Checks if the signal is SIGUSR1
printf("\nSIGUSR1 received!\n"); // Prints a message when SIGUSR1 is received
}

int main() // Main function starts here
{

// Connects SIGINT to handle_signal()
// SIGINT is usually generated by Ctrl+C
signal(SIGINT, handle_signal);

// Connects SIGTERM to handle_signal()
// SIGTERM is used to request process termination
signal(SIGTERM, handle_signal);
                              
// Connects SIGUSR1 to handle_signal()
// SIGUSR1 is a user-defined signal  
signal(SIGUSR1, handle_signal);

printf("Program started...\n"); // Displays that the program has started
printf("Process ID: %d\n", getpid()); // getpid() gives the process ID of the program
while (1) // Infinite loop; keeps the program running
{
printf("Program is running...\n"); // Displays that the program is still running
sleep(20); // Waits for 3 seconds
}
return 0; // Ends the program successfully
}

